"""
MCP Tool: generate_grpc_client

Generates matching client-side gRPC invocation logic to replace old HTTP client calls.

Given a .proto text or a GrpcMigrationProposal JSON path, this tool produces:
  - A fully-typed Python gRPC client class
  - Per-RPC method stubs with channel setup and TLS options
  - A usage example showing how to replace old requests.get/post calls
  - grpc_tools.protoc compile command to generate the _pb2 modules
"""
from __future__ import annotations

import json
import re
import tempfile
from pathlib import Path
from typing import Any

from mcp.templates.grpc_client import GRPC_CLIENT_TEMPLATE
from mcp.templates.interceptors import INTERCEPTORS_TEMPLATE


# ── Proto parsing helpers ─────────────────────────────────────────────────────

def _extract_service_name(proto_text: str) -> str:
    """Pull the service name from proto3 text."""
    m = re.search(r"service\s+(\w+)\s*\{", proto_text)
    return m.group(1) if m else "MigratedService"


def _extract_rpcs(proto_text: str) -> list[dict[str, str]]:
    """Extract rpc method definitions from proto3 text."""
    pattern = re.compile(r"rpc\s+(\w+)\s*\((\w+)\)\s*returns\s*\((\w+)\)")
    return [
        {"name": m.group(1), "request": m.group(2), "response": m.group(3)}
        for m in pattern.finditer(proto_text)
    ]


def _extract_messages(proto_text: str) -> dict[str, list[dict[str, str]]]:
    """Extract message field definitions from proto3 text."""
    messages: dict[str, list[dict[str, str]]] = {}
    msg_pattern = re.compile(r"message\s+(\w+)\s*\{([^}]*)\}", re.DOTALL)
    field_pattern = re.compile(r"(repeated\s+)?([\w.]+)\s+(\w+)\s*=\s*(\d+)\s*;")
    for msg_match in msg_pattern.finditer(proto_text):
        msg_name = msg_match.group(1)
        body = msg_match.group(2)
        fields = []
        for f in field_pattern.finditer(body):
            repeated = bool(f.group(1))
            fields.append(
                {
                    "proto_type": ("repeated " if repeated else "") + f.group(2),
                    "name": f.group(3),
                    "field_number": f.group(4),
                }
            )
        messages[msg_name] = fields
    return messages


def _pascal_to_snake(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


# ── Code generation ───────────────────────────────────────────────────────────

def _generate_client_code(
    proto_text: str,
    service_name: str,
    rpcs: list[dict[str, str]],
    messages: dict[str, list[dict[str, str]]],
    module_name: str,
) -> str:
    """Generate a complete Python gRPC client module."""
    snake_service = _pascal_to_snake(service_name)

    lines = [
        '"""',
        f"gRPC client for {service_name}.",
        "Generated by autonomous-api-migration-engineer MCP.",
        "Replace HTTP client calls with this strongly-typed gRPC client.",
        "",
        "Prerequisites:",
        "    pip install grpcio grpcio-tools",
        f"    python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/{module_name}.proto",
        '"""',
        "from __future__ import annotations",
        "",
        "import grpc",
        f"# from proto import {module_name}_pb2 as pb2",
        f"# from proto import {module_name}_pb2_grpc as pb2_grpc",
        "",
        "",
    ]

    # Class definition
    lines += [
        f"class {service_name}Client:",
        f'    """',
        f"    Drop-in gRPC replacement for HTTP calls to {service_name}.",
        f"",
        f"    Usage:",
        f"        client = {service_name}Client(target='localhost:50051')",
    ]

    # Usage examples per RPC
    for rpc in rpcs:
        req_fields = messages.get(rpc["request"], [])
        kwargs_example = ", ".join(f"{f['name']}=..." for f in req_fields[:2])
        lines.append(f"        response = client.{_pascal_to_snake(rpc['name'])}({kwargs_example})")

    lines += [
        f'    """',
        "",
        "    def __init__(",
        "        self,",
        "        target: str = 'localhost:50051',",
        "        *,",
        "        use_tls: bool = False,",
        "        credentials: grpc.ChannelCredentials | None = None,",
        "        options: list[tuple[str, object]] | None = None,",
        "    ) -> None:",
        "        opts = options or [",
        "            ('grpc.max_send_message_length', 10 * 1024 * 1024),",
        "            ('grpc.max_receive_message_length', 10 * 1024 * 1024),",
        "        ]",
        "        if use_tls:",
        "            creds = credentials or grpc.ssl_channel_credentials()",
        "            self._channel = grpc.secure_channel(target, creds, options=opts)",
        "        else:",
        "            self._channel = grpc.insecure_channel(target, options=opts)",
        f"        # self._stub = pb2_grpc.{service_name}Stub(self._channel)",
        "",
    ]

    # Per-RPC method stubs
    for rpc in rpcs:
        method_name = _pascal_to_snake(rpc["name"])
        req_msg = rpc["request"]
        resp_msg = rpc["response"]
        req_fields = messages.get(req_msg, [])
        param_sig = ", ".join(
            f"{f['name']}: {_proto_type_to_py(f['proto_type'])}" for f in req_fields
        ) or "**kwargs: object"

        lines += [
            f"    def {method_name}(self, {param_sig}) -> dict:",
            f'        """',
            f"        Calls {service_name}.{rpc['name']} RPC.",
            f"",
            f"        Request message:  {req_msg}",
            f"        Response message: {resp_msg}",
            f'        """',
            f"        # request = pb2.{req_msg}(",
        ]
        for f in req_fields:
            lines.append(f"        #     {f['name']}={f['name']},")
        lines += [
            f"        # )",
            f"        # response = self._stub.{rpc['name']}(request, timeout=30)",
            f"        # return MessageToDict(response)",
            f"        raise NotImplementedError(",
            f"            'Run grpc_tools.protoc to generate pb2 modules, then uncomment the lines above.'",
            f"        )",
            "",
        ]

    # Context manager
    lines += [
        "    def close(self) -> None:",
        '        """Close the gRPC channel."""',
        "        self._channel.close()",
        "",
        f"    def __enter__(self) -> '{service_name}Client':",
        "        return self",
        "",
        "    def __exit__(self, *_: object) -> None:",
        "        self.close()",
        "",
    ]

    return "\n".join(lines)


def _proto_type_to_py(proto_type: str) -> str:
    mapping = {
        "string": "str",
        "int32": "int",
        "int64": "int",
        "bool": "bool",
        "double": "float",
        "float": "float",
        "bytes": "bytes",
        "repeated string": "list[str]",
    }
    return mapping.get(proto_type, "object")


# ── Public tool function ───────────────────────────────────────────────────────

def generate_grpc_client(
    proto_content: str | None = None,
    proposal_path: str | None = None,
    module_name: str = "service",
    output_path: str | None = None,
    include_interceptors: bool = True,
) -> dict[str, Any]:
    """
    Generate Python gRPC client stubs to replace old HTTP client calls.

    Provide either:
    - proto_content: raw proto3 text string
    - proposal_path: path to a GrpcMigrationProposal JSON file

    Args:
        proto_content: Raw proto3 text to generate the client from.
        proposal_path: Path to a GrpcMigrationProposal JSON (contains proposed_proto field).
        module_name: The proto module name used for import paths (default: "service").
        output_path: If provided, write the generated client to this .py file.
        include_interceptors: If True, include the interceptor boilerplate in the response.

    Returns:
        A dict with:
          - client_code: the generated Python gRPC client module
          - service_name: detected service name from the proto
          - rpc_methods: list of generated method names
          - protoc_command: the grpc_tools.protoc command to generate _pb2 modules
          - output_path: where the file was written (or null)
          - interceptors_template: interceptor boilerplate (if include_interceptors)
    """
    # ── Resolve proto source ──────────────────────────────────────────────────
    if proto_content is None and proposal_path is not None:
        raw = json.loads(Path(proposal_path).read_text())
        proto_content = raw.get("proposed_proto", "")
        if not proto_content:
            raise ValueError("proposal_path JSON has no 'proposed_proto' field.")
    elif proto_content is None:
        raise ValueError("Provide either proto_content or proposal_path.")

    # ── Parse proto ───────────────────────────────────────────────────────────
    service_name = _extract_service_name(proto_content)
    rpcs = _extract_rpcs(proto_content)
    messages = _extract_messages(proto_content)

    if not rpcs:
        raise ValueError("No rpc methods found in the provided proto content.")

    # ── Generate client code ──────────────────────────────────────────────────
    client_code = _generate_client_code(proto_content, service_name, rpcs, messages, module_name)

    # ── Optionally write to file ──────────────────────────────────────────────
    written_path: str | None = None
    if output_path:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(client_code)
        written_path = str(out.resolve())

    protoc_cmd = (
        f"python -m grpc_tools.protoc "
        f"-I. --python_out=. --grpc_python_out=. proto/{module_name}.proto"
    )

    result: dict[str, Any] = {
        "client_code": client_code,
        "service_name": service_name,
        "rpc_methods": [_pascal_to_snake(r["name"]) for r in rpcs],
        "protoc_command": protoc_cmd,
        "output_path": written_path,
    }

    if include_interceptors:
        result["interceptors_template"] = INTERCEPTORS_TEMPLATE
        result["interceptors_note"] = (
            "interceptors_template contains production-ready logging, auth, and retry "
            "interceptors. Wire them in using build_server() before deploying."
        )

    return result
