"""
Python gRPC client stub boilerplate template.

Provides a ready-to-use client class that replaces HTTP client calls
with strongly-typed gRPC channel invocations.
"""

GRPC_CLIENT_TEMPLATE = '''\
"""
gRPC Client — generated by autonomous-api-migration-engineer MCP.

Replaces HTTP client calls to <ServiceName> with gRPC channel invocations.
Adapt the stub class, channel target, and TLS settings before use.

Prerequisites:
    pip install grpcio grpcio-tools
    python -m grpc_tools.protoc \\
        -I. --python_out=. --grpc_python_out=. \\
        proto/<service_name>.proto
"""
from __future__ import annotations

import grpc

# Replace these imports with your actual generated _pb2 and _pb2_grpc modules.
# from proto import <service_name>_pb2 as pb2
# from proto import <service_name>_pb2_grpc as pb2_grpc


class <ServiceName>GrpcClient:
    """
    Drop-in replacement for the HTTP client targeting <ServiceName>.

    Usage:
        client = <ServiceName>GrpcClient(target="localhost:50051")
        response = client.<rpc_method>(<field>=<value>)
    """

    def __init__(
        self,
        target: str = "localhost:50051",
        *,
        use_tls: bool = False,
        credentials: grpc.ChannelCredentials | None = None,
        options: list[tuple[str, object]] | None = None,
    ) -> None:
        opts = options or [
            ("grpc.max_send_message_length", 10 * 1024 * 1024),
            ("grpc.max_receive_message_length", 10 * 1024 * 1024),
        ]
        if use_tls:
            creds = credentials or grpc.ssl_channel_credentials()
            self._channel = grpc.secure_channel(target, creds, options=opts)
        else:
            self._channel = grpc.insecure_channel(target, options=opts)

        # self._stub = pb2_grpc.<ServiceName>GrpcStub(self._channel)

    # -----------------------------------------------------------------------
    # Replace with your actual RPC methods, generated from the .proto file.
    # Each method should map 1-to-1 from the old HTTP endpoint.
    # -----------------------------------------------------------------------

    def <rpc_method>(self, **kwargs) -> dict:
        """
        Replaces: <HTTP_METHOD> <path>

        Args:
            **kwargs: Fields matching the proto request message.

        Returns:
            dict representation of the proto response message.
        """
        # request = pb2.<RpcMethod>Request(**kwargs)
        # response = self._stub.<RpcMethod>(request, timeout=30)
        # return MessageToDict(response)
        raise NotImplementedError("Replace this stub with actual generated gRPC call.")

    def close(self) -> None:
        """Close the gRPC channel and release resources."""
        self._channel.close()

    def __enter__(self) -> "<ServiceName>GrpcClient":
        return self

    def __exit__(self, *_: object) -> None:
        self.close()
'''

GRPC_CLIENT_DESCRIPTION = """\
Python gRPC client stub template to replace HTTP client calls.

Provides:
- <ServiceName>GrpcClient class with optional TLS support
- Channel lifecycle management (context manager)
- Per-RPC method stubs with docstrings mapping to original REST endpoints
- Max message size configuration
- Usage instructions for grpc_tools.protoc code generation

Replace all <Placeholder> tokens with your actual service and method names.
"""
