"""
gRPC interceptor boilerplate templates (server-side and client-side).

Provides logging, auth, error-mapping, and retry interceptors
for Python gRPC services generated during REST-to-gRPC migration.
"""

INTERCEPTORS_TEMPLATE = '''\
"""
gRPC Interceptors — generated by autonomous-api-migration-engineer MCP.
Adapt and extend as needed. Do not promote to production without review.
"""
from __future__ import annotations

import logging
import time
import grpc

logger = logging.getLogger(__name__)


# ===========================================================================
# Server-side: Logging interceptor
# ===========================================================================
class LoggingServerInterceptor(grpc.ServerInterceptor):
    """Logs every incoming RPC with method name, latency, and final status."""

    def intercept_service(self, continuation, handler_call_details):
        method = handler_call_details.method
        start = time.perf_counter()

        def wrapper(request, context):
            try:
                response = continuation(handler_call_details)(request, context)
                elapsed = (time.perf_counter() - start) * 1000
                logger.info("gRPC %s OK (%.1f ms)", method, elapsed)
                return response
            except Exception as exc:
                elapsed = (time.perf_counter() - start) * 1000
                logger.error("gRPC %s ERROR (%.1f ms): %s", method, elapsed, exc)
                raise

        handler = continuation(handler_call_details)
        if handler is None:
            return None
        return grpc.unary_unary_rpc_method_handler(
            wrapper,
            request_deserializer=handler.request_deserializer,
            response_serializer=handler.response_serializer,
        )


# ===========================================================================
# Server-side: Auth interceptor (Bearer token validation)
# ===========================================================================
class AuthServerInterceptor(grpc.ServerInterceptor):
    """Validates Bearer token from gRPC metadata. Replace verify() with real logic."""

    SKIP_METHODS: set[str] = {"HealthCheck"}

    def intercept_service(self, continuation, handler_call_details):
        method = handler_call_details.method.rsplit("/", 1)[-1]
        if method in self.SKIP_METHODS:
            return continuation(handler_call_details)

        def wrapper(request, context):
            metadata = dict(context.invocation_metadata())
            token = metadata.get("authorization", "").removeprefix("Bearer ").strip()
            if not self._verify(token):
                context.abort(grpc.StatusCode.UNAUTHENTICATED, "Invalid or missing token.")
            return continuation(handler_call_details)(request, context)

        handler = continuation(handler_call_details)
        if handler is None:
            return None
        return grpc.unary_unary_rpc_method_handler(
            wrapper,
            request_deserializer=handler.request_deserializer,
            response_serializer=handler.response_serializer,
        )

    def _verify(self, token: str) -> bool:
        # TODO: Replace with JWT validation, OAuth introspection, etc.
        return bool(token)


# ===========================================================================
# Client-side: Retry interceptor (exponential back-off)
# ===========================================================================
class RetryClientInterceptor(grpc.UnaryUnaryClientInterceptor):
    """Retries UNAVAILABLE / DEADLINE_EXCEEDED responses with exponential back-off."""

    RETRYABLE = {grpc.StatusCode.UNAVAILABLE, grpc.StatusCode.DEADLINE_EXCEEDED}
    MAX_ATTEMPTS = 3
    BASE_DELAY = 0.5  # seconds

    def intercept_unary_unary(self, continuation, client_call_details, request):
        import time as _time
        last_error = None
        for attempt in range(self.MAX_ATTEMPTS):
            response = continuation(client_call_details, request)
            if response.code() not in self.RETRYABLE:
                return response
            last_error = response
            delay = self.BASE_DELAY * (2 ** attempt)
            logger.warning("Retrying %s in %.1fs (attempt %d)", client_call_details.method, delay, attempt + 1)
            _time.sleep(delay)
        return last_error


# ===========================================================================
# Server startup helper
# ===========================================================================
def build_server(servicer, add_servicer_fn, port: int = 50051) -> grpc.Server:
    """Convenience factory that wires all interceptors and starts the server."""
    server = grpc.server(
        grpc.futures.ThreadPoolExecutor(max_workers=10),
        interceptors=[LoggingServerInterceptor(), AuthServerInterceptor()],
    )
    add_servicer_fn(servicer, server)
    server.add_insecure_port(f"[::]:{port}")
    logger.info("gRPC server listening on port %d", port)
    return server
'''

INTERCEPTORS_DESCRIPTION = """\
Production-ready gRPC interceptor boilerplate for migrated services.

Includes:
- LoggingServerInterceptor  — logs every RPC with method, latency, status
- AuthServerInterceptor     — Bearer token validation (swap _verify() for your auth logic)
- RetryClientInterceptor    — exponential back-off for UNAVAILABLE / DEADLINE_EXCEEDED
- build_server()            — convenience factory wiring all interceptors together

Generated by the autonomous-api-migration-engineer MCP. Requires review before production use.
"""
