"""
Standard .proto file header boilerplate template.

Use this as the canonical header for every generated .proto file in the migration.
"""

PROTO_HEADER_TEMPLATE = '''\
// ============================================================
// AUTO-GENERATED by autonomous-api-migration-engineer MCP
// DO NOT EDIT — regenerate via the generate_proto MCP tool.
// Requires human approval before promotion to production.
// ============================================================

syntax = "proto3";

// ---------------------------------------------------------------------------
// Package declaration
// Replace <org>, <service>, and <version> with your actual values.
// ---------------------------------------------------------------------------
package <org>.<service>.v<version>;

// ---------------------------------------------------------------------------
// Go package option — delete if not targeting Go.
// ---------------------------------------------------------------------------
option go_package = "github.com/<org>/<service>/v<version>";

// ---------------------------------------------------------------------------
// Java options — delete if not targeting Java/Kotlin.
// ---------------------------------------------------------------------------
option java_package = "com.<org>.<service>.v<version>";
option java_multiple_files = true;
option java_outer_classname = "<Service>Proto";

// ---------------------------------------------------------------------------
// Import commonly needed well-known types.
// Remove imports you do not use.
// ---------------------------------------------------------------------------
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
'''

PROTO_HEADER_DESCRIPTION = """\
Standard .proto file header template used by the migration engineer.

Replace placeholders:
  <org>      — your organization / GitHub owner
  <service>  — snake_case service name
  <version>  — integer API version (e.g. 1)
  <Service>  — PascalCase service name for Java outerClassname

The header enforces proto3 syntax, sets multi-language package options,
and imports the most commonly required well-known types.
"""
